### ISSUE TITLE
error on flatten step

### ISSUE THREAD

**Issue by darraghdog** [flyyufelix/cnn_finetune#1]
Hi Felix, thanks for putting the repo together, I am trying to get one of the models working -- vgg16 -- but getting an error on the flatten step as seen below. In my code on compiling the model I inputted number of channels; are you using a backend of theano or tensorflow ? I wonder could this me my issue.

```
ValueErrorTraceback (most recent call last)
<ipython-input-6-1af69e06c865> in <module>()
     11 
     12 # Load our model
---> 13 model = vgg_std16_model(img_rows, img_cols, channel, num_class)
     14 
     15 # Start Fine-tuning

<ipython-input-2-25fab191ca91> in vgg_std16_model(img_rows, img_cols, channel, num_class)
     49 
     50     # Add Fully Connected Layer
---> 51     model.add(Flatten())
     52     model.add(Dense(4096, activation='relu'))
     53     model.add(Dropout(0.5))

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/models.pyc in add(self, layer)
    453                           output_shapes=[self.outputs[0]._keras_shape])
    454         else:
--> 455             output_tensor = layer(self.outputs[0])
    456             if isinstance(output_tensor, list):
    457                 raise TypeError('All layers in a Sequential model '

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in __call__(self, inputs, **kwargs)
    557             # Infering the output shape is only relevant for Theano.
    558             if all([s is not None for s in _to_list(input_shape)]):
--> 559                 output_shape = self.compute_output_shape(input_shape)
    560             else:
    561                 if isinstance(input_shape, list):

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/layers/core.pyc in compute_output_shape(self, input_shape)
    486             raise ValueError('The shape of the input to "Flatten" '
    487                              'is not fully defined '
--> 488                              '(got ' + str(input_shape[1:]) + '. '
    489                              'Make sure to pass a complete "input_shape" '
    490                              'or "batch_input_shape" argument to the first '

ValueError: The shape of the input to "Flatten" is not fully defined (got (0, 3, 512). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.
```

**Comment by flyyufelix** [comment]
I used Keras 1.2.2. For VGG-16 only Theano backend is supported. From the error traceback I suspect that you use an input size that is not (x, 3,224,224)? This will break the fully connected layer since its weight is dependent on the input size.

**Comment by darraghdog** [comment]
Thanks, I will try it later today with the 3x224x224 images...

**Comment by darraghdog** [comment]
HI Felix, This seems to work - I went back to Keras 1.2.2 from 2.x; this sorted out the flatten issue, and then switching to 224x224 images got it working. Quick question, are all the weights files only for 224x224 images ?Do you see any way to use the transfer learning with different size images. Thanks!

**Comment by flyyufelix** [comment]
For VGG-16, the shape of the weight tensor for the fully connected layer depends on the input size. But yes you can do transfer learning with a different input resolution, say 400x400. What you need to do is to replace the fully connected layer with a global average pooling layer. Add the GAP layer after the last convolutional layer. I tried it before the model works as well as the original VGG-16.
