### ISSUE TITLE
layers of resnet_101.py

### ISSUE THREAD

**Issue by yfor1008** [flyyufelix/cnn_finetune#16]
In article, the `conv3_x` parameter of `101-layer` is `4`, 
but the code is `3`, 
```python
x = conv_block(x, 3, [128, 128, 512], stage=3, block='a')
for i in range(1,3):
     x = identity_block(x, 3, [128, 128, 512], stage=3, block='b'+str(i))
```

**Comment by flyyufelix** [comment]
Can you elaborate on which parameter you are referring to? And also mind citing the article?

The ResNet-101 implementation here in this repo follows the original implementation in Caffe provided by the author of ResNet (https://github.com/KaimingHe/deep-residual-networks)

**Comment by yfor1008** [comment]
the article is cited here [https://arxiv.org/pdf/1512.03385.pdf](https://arxiv.org/pdf/1512.03385.pdf), 
in `Table 1` of the article, the number of  blocks in  `conv3_x`  row and `101-layer` column is `4`, but in https://github.com/flyyufelix/cnn_finetune/blob/d04821e1cd6b59b4fa7cbd2190b1001f6fdff48f/resnet_101.py#L136

the blocks number is `3`

**Comment by flyyufelix** [comment]
Thanks for pointing that out. Yes, I indeed made a typo in the for loop. Should be 4 instead of 3. Code is fixed now.
