### ISSUE TITLE
dimension mismatch with tensorflow background for resnet 101 model

### ISSUE THREAD

**Issue by deepakanandece** [flyyufelix/cnn_finetune#17]
ValueError: Negative dimension size caused by subtracting 7 from 3 for 'avg_pool/AvgPool' (op: 'AvgPool') with input shapes: [?,3,3,2048]

**Comment by yfor1008** [comment]
What is the image size? the image size of the model is 224

**Comment by deepakanandece** [comment]
Thanks for the reply. Do you think resizing an image and then applying resnet will make a vast difference to the features learnt? I am talking in terms of the information lost when upsampling or downsampling is done.

**Comment by yfor1008** [comment]
If you want to use other sizes of images, then it is necessary to modify the following places：
```python
x_newfc = AveragePooling2D((7, 7), name='avg_pool')(x)
x_newfc = Flatten()(x_newfc)
x_newfc = Dense(num_classes, activation='softmax', name='fc8')(x_newfc)
```
**change to：**
```python
x_newfc = GlobalAveragePooling2D(name='avg_pool')(x)
x_newfc = Dense(num_classes, activation='softmax', name='fc8')(x_newfc)
```
