### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 512 for 'Assign_78' (op: 'Assign') with input shapes: [1,1,128,512], [512,256,1,1].

### ISSUE THREAD

**Issue by qilicun** [flyyufelix/cnn_finetune#19]
When I use resnet_50, this error happened, can anyone help me? Thansk!

**Comment by Coderx7** [comment]
@qilicun  did you figure it out? I'm getting the same error!
@flyyufelix 
`ValueError: Dimension 2 in both shapes must be equal, but are 128 and 256 for 'Assign_78' (op: 'Assign') with input shapes: [1,1,128,512], [1,1,256,512].`

**Comment by qilicun** [comment]
@Coderx7 No，I didn't, do you have any ideas?

**Comment by Coderx7** [comment]
@qilicun We are on the same boat buddy. could'nt find any clue about what could be wrong! 
Im running the given example, without altering anything, yet it fails!

**Comment by Coderx7** [comment]
@qilicun : OK, I used the script from [this post](https://github.com/fchollet/keras/issues/3622#issuecomment-310140079), and it is running just fine so far!
give that a try

**Comment by flyyufelix** [comment]
Make sure the input tensors are of the right dimension:

For Theano backend: 

('X_train: ', (num_training_samples, 3, 224, 224))
('X_valid:', (num_validation_samples, 3, 224, 224))
('Y_train:', (num_train_samples, num_classes))
('Y_valid:', (num_validation_samples, num_classes))

For Tensorflow backend : 

('X_train: ', (num_training_samples, 224, 224, 3))
('X_valid:', (num_validation_samples, 224, 224, 3))
('Y_train:', (num_train_samples, num_classes))
('Y_valid:', (num_validation_samples, num_classes))

You can examine the dimension of inputs in this line `X_train, Y_train, X_valid, Y_valid = load_cifar10_data(img_rows, img_cols)` and compare it against yours.

**Comment by josh-marsh** [comment]
Hey, I've run into this same issue and the input shapes are all correct. Is it an issue if my data has only one colour channel, i.e  the input shape is:
('X_train: ', (num_training_samples, 267, 267, 1))
('X_valid:', (num_validation_samples, 267, 267, 1))
('Y_train:', (num_train_samples, num_classes))
('Y_valid:', (num_validation_samples, num_classes))

**Comment by hiroshiperera** [comment]
getting the same error ... Could anyone solve this out?

**Comment by annanurov** [comment]
This error pops up when I save a model based on a pre-trained Keras model (e.g. VGG16):
`model.save(save_model_file_path)`
and the load it again:
`model = load_model(save_model_file_path)`

seemingly, all params and dimensions should be same. How to solve?

**Comment by tomaszkaliciak** [comment]
@annanurov Did you find solution?

**Comment by diliplilaramani** [comment]
Anyone found a solution? Same error when I saved a vgg16 model and load it again.

**Comment by KateShan** [comment]
I am stuck with the same problem. I haven't got the resolution yet, but try to look for config.py file for hints.

**Comment by dtnzj** [comment]
Solved!
I generate the train.txt file with the classes (A) of my own dataset, but gives a default classes(B) file in the train process. This lead to that the weight file works for a model of classes B, but only the dataset of class A given. 
So, please just recheck your code carefully again.

**Comment by world4jason** [comment]
same error here lol 
anyone solved?

**Comment by arunikayadav42** [comment]
has anybody got a solution to overcome the error?Please do tell

**Comment by NguyenVanThanhHust** [comment]
For vgg 16 and my custom dataset, i met a similar error. I'm not sure this can help but i think you can try( i fix with this):
1. set data_format in Image DataGenerator to be : channels_first
2. Fix input size to (224, 224, 3).

This error might come from incompatible input shape with predefined network architecture.
