### ISSUE TITLE
Problem with finetuning DenseNet with my own data

### ISSUE THREAD

**Issue by htuncer** [flyyufelix/cnn_finetune#20]
Hi @flyyufelix ,
I am trying to finetune DenseNet161.py with custom png images. I am getting an error.  I compared the cifar10.load_data() with my own load_data(). The output shapes and content types are the same.  I'd be happy if you can take a look at the error and my code below.  Thanks in advance for your time and help.

**ERROR:**
ValueError: You are passing a target array of shape (2, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:

 from keras.utils.np_utils import to_categorical
 y_binary = to_categorical(y_int)

**MY CODE:**
```
def load_data(img_rows, img_cols):
    num_classes = 1
    img1=cv2.resize(cv2.imread('images/vehicle/image0451.png'), (img_rows, img_cols)).astype(np.float32)
    img2=cv2.resize(cv2.imread('images/vehicle/image0452.png'), (img_rows, img_cols)).astype(np.float32)
    img3=cv2.resize(cv2.imread('images/vehicle/image0453.png'), (img_rows, img_cols)).astype(np.float32)

    for x in (img1,img2,img3):
        x[:, :, 0] -= 103.939
        x[:, :, 1] -= 116.779
        x[:, :, 2] -= 123.68

    X_train = np.array([img1,img2])
    X_valid = np.array([img3])

    Y_train = np.array([[0],[0]])
    Y_valid = np.array([[0]])

    # Transform targets to keras compatible format
    Y_train = np_utils.to_categorical(Y_train, num_classes)
    Y_valid = np_utils.to_categorical(Y_valid, num_classes)

    return X_train, Y_train, X_valid, Y_valid

**Comment by flyyufelix** [comment]
From the error message, it looks like the problem is in the dimension of the targets. Keras expects targets to be binary matrices with dimension (samples, classes). Hence, if what you are building is a binary classifier your targets should be of dimension (samples, 2). In the load_data() function the num_classes variable should be set to 2 instead of 1.

**Comment by htuncer** [comment]
Your suggestion worked. I thought num_classes will be 1 as I had only 1 class. Thanks very much.
