### ISSUE TITLE
Image input shape issue

### ISSUE THREAD

**Issue by Rabia-Metis** [flyyufelix/cnn_finetune#25]
I am using resnet-152 architecture and training input of size 224x224 and 331 images with tensor-flow backend but keep getting this error: 
**ValueError: Error when checking input: expected data to have shape (None, 224, 224, 3) but got array with shape (331, 3, 224, 224)**
I tried setting image data format to channel_first and channel_last but its not working either way
Kindly help me out

**Comment by hiroshiperera** [comment]
Hi were you abe to find an answer for this
