### ISSUE TITLE
load_data returns None?

### ISSUE THREAD

**Issue by kevinkit** [flyyufelix/cnn_finetune#3]
Hello, 

This is actually a great tutorial repo, however I cannot get my head around the load_data functions ? They always just return None ?

**Comment by flyyufelix** [comment]
You have to implement the load_data() function for your own dataset. The function should return the following: 

X_train, X_valid, Y_train, Y_valid = load_data()

where X_train, X_valid, Y_train, Y_valid are numpy arrays.

**Comment by kevinkit** [comment]
I thought about that - but was not quite sure if this was intended, since it is not mentioned anywhere.


Thank you
