### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by michirup** [flyyufelix/cnn_finetune#53]
Does someone else have this issue? The code seems to stop just before this line `x = conv_block(x, 3, [64, 64, 256], stage=2, block='a', strides=(1, 1))` and this is the error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-16-4ef36ddf89c4> in <module>()
    340 
    341     # Load our model
--> 342     model_ = resnet101_model(img_rows, img_cols, channel, num_classes)
    343 
    344     # Start Fine-tuning

<ipython-input-16-4ef36ddf89c4> in resnet101_model(img_rows, img_cols, color_type, num_classes)
    138     print('ok7')
    139 
--> 140     x = conv_block(x, 3, [64, 64, 256], stage=2, block='a', strides=(1, 1))
    141     print('ok8')
    142     x = identity_block(x, 3, [64, 64, 256], stage=2, block='b')

<ipython-input-16-4ef36ddf89c4> in conv_block(input_tensor, kernel_size, filters, stage, block, strides)
     90     shortcut = Scale(axis=bn_axis, name=scale_name_base + '1')(shortcut)
     91 
---> 92     x = merge([x, shortcut], mode='sum', name='res' + str(stage) + block)
     93     x = Activation('relu', name='res' + str(stage) + block + '_relu')(x)
     94     return x

TypeError: 'module' object is not callable
```

The same happens for _resnet152_model_

**Comment by efferre99** [comment]
I had the same problem. I solved replacing
 concat_feat = merge([concat_feat, x], mode='concat', concat_axis=concat_axis, name='concat_'+str(stage)+'_'+str(branch))
with
        concat_feat = Concatenate( axis=-1)([concat_feat, x])

Maybe in conv_block you have to replace also Convolution2D with Conv2D

**Comment by michirup** [comment]
Thanks for your help @efferre99 . In my case (Resnet networks) I have substituted in conv_block:

`x = merge([x, shortcut], mode='sum', name='res' + str(stage) + block)`
with 
` x = Add()([x, shortcut])`

and in identity block:
`x = merge([x, input_tensor], mode='sum', name='res' + str(stage) + block)`
with 
`x = Add()([x, input_tensor])`

Pay also attention to import Add at the beginning!
