### ISSUE TITLE
Image Preprocessing for ImageNet models.

### ISSUE THREAD

**Issue by syeddanish41** [flyyufelix/cnn_finetune#6]
Hi,

As all of these models are ImageNet model, I was wondering if you used similar kind of image processing as used by these models otherwise, model weights would be different in either case. 

Thanks

**Comment by flyyufelix** [comment]
Yes, different models might use different preprocessing techniques. For more detail on how the models are trained, I've included a reference link to the original repo for each model. For example, for VGG16 pretrained model you can find the reference link in vgg16.py: 

```
def vgg16_model(img_rows, img_cols, channel=1, num_classes=None):
    """VGG 16 Model for Keras

    Model Schema is based on 
    https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3

    ImageNet Pretrained Weights 
    https://drive.google.com/file/d/0Bz7KyqmuGsilT0J5dmRCM0ROVHc/view?usp=sharing
```
