### ISSUE TITLE
How to use resnet101 for batch training?

### ISSUE THREAD

**Issue by akshittyagi** [flyyufelix/cnn_finetune#8]
I am using resnet 101 for batch training for an input of 1900 training images with 224,224,3 dimensions. The labels are pixelwise probability maps of 2 classes, so a label is 224,224,2 in shape.
Now when I use this model with an img_input = Input(shape=(1900,224,224,3)). But when this is passed to the next layer of ZeroPadding2D the img_input gets 5 dimensions somehow.

This being the error:
```
ValueError: Input 0 is incompatible with layer conv1_zeropadding: expected ndim=4, found ndim=5
```

Would be great if you could help

**Comment by flyyufelix** [comment]
For Keras, you don't have to specify number of samples in the img_input. So the input shape to the model should be (224,224,3)

**Comment by akshittyagi** [comment]
Thanks. It worked.
